using Mexc.Net.Objects.Models;
using Mexc.Net.Objects.Models.Futures;
using Mexc.Net.Objects.Models.Spot;
using Mexc.Net.Objects.Sockets.Models;

namespace Mexc.Net.Converters
{
    [JsonSerializable(typeof(MexcPlaceOrderRequest[]))]
    [JsonSerializable(typeof(MexcOrderResult[]))]
    [JsonSerializable(typeof(MexcFuturesResponse<long>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcContract[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<string[]>))]
    // End manual defined attributes

    [JsonSerializable(typeof(MexcUpdate<MexcStreamMiniTick[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcWithdrawAddress[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcDustLog[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcInternalTransfer[]>))]
    [JsonSerializable(typeof(MexcResult<string[]>))]
    [JsonSerializable(typeof(MexcRows<MexcTransfer[]>))]
    [JsonSerializable(typeof(MexcUpdate<MexcTradeUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcKlineUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamOrderBook>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamBookTick>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamMiniTick>))]
    [JsonSerializable(typeof(MexcUpdate<MexcAccountUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcUserOrderUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcUserTradeUpdate>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(MexcResult<MexcDeductStatus>))]
    [JsonSerializable(typeof(MexcResult<MexcTradeFee>))]
    [JsonSerializable(typeof(MexcStreamTrade[]))]
    [JsonSerializable(typeof(MexcResult[]))]
    [JsonSerializable(typeof(MexcAccountInfo[]))]
    [JsonSerializable(typeof(MexcAccountBalance[]))]
    [JsonSerializable(typeof(MexcAccountUpdate[]))]
    [JsonSerializable(typeof(MexcAggregatedTrade[]))]
    [JsonSerializable(typeof(MexcAveragePrice[]))]
    [JsonSerializable(typeof(MexcBookPrice[]))]
    [JsonSerializable(typeof(MexcDeductStatus[]))]
    [JsonSerializable(typeof(MexcDeposit[]))]
    [JsonSerializable(typeof(MexcDepositAddress[]))]
    [JsonSerializable(typeof(MexcDustLogDetails[]))]
    [JsonSerializable(typeof(MexcDustResult[]))]
    [JsonSerializable(typeof(MexcFailedDust[]))]
    [JsonSerializable(typeof(MexcEligibleDust[]))]
    [JsonSerializable(typeof(MexcEtf[]))]
    [JsonSerializable(typeof(MexcExchangeInfo[]))]
    [JsonSerializable(typeof(MexcId[]))]
    [JsonSerializable(typeof(MexcKline[]))]
    [JsonSerializable(typeof(MexcKycStatus[]))]
    [JsonSerializable(typeof(MexcListenKey[]))]
    [JsonSerializable(typeof(MexcOrder[]))]
    [JsonSerializable(typeof(MexcOrderBook[]))]
    [JsonSerializable(typeof(MexcOrderBookEntry[]))]
    [JsonSerializable(typeof(MexcPrice[]))]
    [JsonSerializable(typeof(MexcServerTime[]))]
    [JsonSerializable(typeof(MexcStreamBookTick[]))]
    [JsonSerializable(typeof(MexcStreamKline[]))]
    [JsonSerializable(typeof(MexcStreamOrderBook[]))]
    [JsonSerializable(typeof(MexcStreamOrderBookEntry[]))]
    [JsonSerializable(typeof(MexcSymbol[]))]
    [JsonSerializable(typeof(MexcTicker[]))]
    [JsonSerializable(typeof(MexcTrade[]))]
    [JsonSerializable(typeof(MexcTradeFee[]))]
    [JsonSerializable(typeof(MexcTransferId[]))]
    [JsonSerializable(typeof(MexcUserAsset[]))]
    [JsonSerializable(typeof(MexcNetwork[]))]
    [JsonSerializable(typeof(MexcUserOrderUpdate[]))]
    [JsonSerializable(typeof(MexcUserTrade[]))]
    [JsonSerializable(typeof(MexcUserTradeUpdate[]))]
    [JsonSerializable(typeof(MexcWithdrawal[]))]
    [JsonSerializable(typeof(MexcKlineUpdate[]))]
    [JsonSerializable(typeof(MexcStreamEvent[]))]
    [JsonSerializable(typeof(MexcTradeUpdate[]))]
    [JsonSerializable(typeof(MexcResponse))]
    [JsonSerializable(typeof(MexcRequest))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class MexcSourceGenerationContext : JsonSerializerContext
    {
    }
}
