using Mexc.Net.Enums;
using Mexc.Net.Objects.Models;
using Mexc.Net.Objects.Models.Futures;
using Mexc.Net.Objects.Models.Protobuf;
using Mexc.Net.Objects.Models.Spot;
using Mexc.Net.Objects.Sockets.Models;
using static Mexc.Net.Objects.Sockets.Subscriptions.MexcFuturesUserSubscription;

namespace Mexc.Net.Converters
{
    [JsonSerializable(typeof(MexcPlaceOrderRequest[]))]
    [JsonSerializable(typeof(MexcOrderResult[]))]
    [JsonSerializable(typeof(MexcFuturesResponse<long>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcContract[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<string[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesOrderBook>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcIndexPrice>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcMarkPrice>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFundingRate>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesKlines>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTrade[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTicker>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTicker[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcRiskFundBalance[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcRiskFundBalanceHistoryPage>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFundingRateHistoryPage>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesBalance[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTransferPage>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcPosition[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFundingRecordPage>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesOrder[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesOrder>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTriggerOrder[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcStopOrder[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesUserTrade[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesFee>))]
    [JsonSerializable(typeof(MexcFuturesResponse))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcLeverage[]>))]
    [JsonSerializable(typeof(MexcFuturesResponse<PositionMode>))]
    [JsonSerializable(typeof(MexcFuturesResponse<Dictionary<string, MexcRiskLimit[]>>))]

    [JsonSerializable(typeof(MexcFuturesRequest))]
    [JsonSerializable(typeof(SubFilter[]))]
    [JsonSerializable(typeof(MexcFuturesResponse<MexcFuturesTicker[]>))]

    [JsonSerializable(typeof(MexcFuturesUpdate<MexcPriceUpdate>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFundingRateUpdate>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesOrderBook>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesTicker>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesTrade>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesStreamKline>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesTickerUpdate[]>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<string>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesBalanceUpdate>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcFuturesOrder>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcPosition>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcRiskLimit>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcAdlUpdate>))]
    [JsonSerializable(typeof(MexcFuturesUpdate<MexcPositionModeUpdate>))]

    // End manual defined attributes

    [JsonSerializable(typeof(MexcUpdate<MexcStreamMiniTick[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcWithdrawAddress[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcDustLog[]>))]
    [JsonSerializable(typeof(MexcPaginated<MexcInternalTransfer[]>))]
    [JsonSerializable(typeof(MexcResult<string[]>))]
    [JsonSerializable(typeof(MexcRows<MexcTransfer[]>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamOrderBook>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamBookTick>))]
    [JsonSerializable(typeof(MexcUpdate<MexcStreamMiniTick>))]
    [JsonSerializable(typeof(MexcUpdate<MexcAccountUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcUserOrderUpdate>))]
    [JsonSerializable(typeof(MexcUpdate<MexcUserTradeUpdate>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(MexcResult<MexcDeductStatus>))]
    [JsonSerializable(typeof(MexcResult<MexcTradeFee>))]
    [JsonSerializable(typeof(MexcStreamTrade[]))]
    [JsonSerializable(typeof(MexcResult[]))]
    [JsonSerializable(typeof(MexcAccountInfo[]))]
    [JsonSerializable(typeof(MexcAccountBalance[]))]
    [JsonSerializable(typeof(MexcAccountUpdate[]))]
    [JsonSerializable(typeof(MexcAggregatedTrade[]))]
    [JsonSerializable(typeof(MexcAveragePrice[]))]
    [JsonSerializable(typeof(MexcBookPrice[]))]
    [JsonSerializable(typeof(MexcDeductStatus[]))]
    [JsonSerializable(typeof(MexcDeposit[]))]
    [JsonSerializable(typeof(MexcDepositAddress[]))]
    [JsonSerializable(typeof(MexcDustLogDetails[]))]
    [JsonSerializable(typeof(MexcDustResult[]))]
    [JsonSerializable(typeof(MexcFailedDust[]))]
    [JsonSerializable(typeof(MexcEligibleDust[]))]
    [JsonSerializable(typeof(MexcEtf[]))]
    [JsonSerializable(typeof(MexcExchangeInfo[]))]
    [JsonSerializable(typeof(MexcId[]))]
    [JsonSerializable(typeof(MexcKline[]))]
    [JsonSerializable(typeof(MexcKycStatus[]))]
    [JsonSerializable(typeof(MexcListenKey[]))]
    [JsonSerializable(typeof(MexcOrder[]))]
    [JsonSerializable(typeof(MexcOrderBook[]))]
    [JsonSerializable(typeof(MexcOrderBookEntry[]))]
    [JsonSerializable(typeof(MexcPrice[]))]
    [JsonSerializable(typeof(MexcServerTime[]))]
    [JsonSerializable(typeof(MexcStreamBookTick[]))]
    [JsonSerializable(typeof(MexcStreamKline[]))]
    [JsonSerializable(typeof(MexcStreamOrderBook[]))]
    [JsonSerializable(typeof(MexcStreamOrderBookEntry[]))]
    [JsonSerializable(typeof(MexcSymbol[]))]
    [JsonSerializable(typeof(MexcTicker[]))]
    [JsonSerializable(typeof(MexcTrade[]))]
    [JsonSerializable(typeof(MexcTradeFee[]))]
    [JsonSerializable(typeof(MexcTransferId))]
    [JsonSerializable(typeof(MexcTransferId[]))]
    [JsonSerializable(typeof(MexcUserAsset[]))]
    [JsonSerializable(typeof(MexcNetwork[]))]
    [JsonSerializable(typeof(MexcUserOrderUpdate[]))]
    [JsonSerializable(typeof(MexcUserTrade[]))]
    [JsonSerializable(typeof(MexcUserTradeUpdate[]))]
    [JsonSerializable(typeof(MexcWithdrawal[]))]
    [JsonSerializable(typeof(MexcStreamEvent[]))]
    [JsonSerializable(typeof(MexcResponse))]
    [JsonSerializable(typeof(MexcRequest))]
    [JsonSerializable(typeof(MexcUpdateMiniTicker))]
    [JsonSerializable(typeof(MexcUpdateMiniTickers))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class MexcSourceGenerationContext : JsonSerializerContext
    {
    }
}
